---
abstract: 'Fast, simple message routing'
author:
  - 'Dana M. Diederich <dana@realms.org>'
build_requires:
  Data::Dumper: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Message-Router
requires:
  Exporter: 0
  Message::Match: 0
  Message::Transform: 0
  Storable: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dana/perl-Message-Router/issues
  homepage: https://github.com/dana/perl-Message-Router
  repository: https://github.com/dana/perl-Message-Router.git
version: 1.143160
